name: Build
on:
  pull_request:
  push:
    branches:
      - release-v2.8
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: make image-build
